bids_dir: './test_bids'
output_dir: '../../../data/lightsheet'


#list of analysis levels in the bids app
analysis_levels: &analysis_levels
 - participant


#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - ''  # if '', then the first rule is run

# Configure components:
# Each entry creates a new component that can be retreived within the workflow
# via `generate_inputs`.
# Filters are used to select paths: each filter has an `entity` key and a
# single value or list of values to select.
# Wildcards are used to mark variable parts of paths. Each wildcard is an
# entity, such as `subject` or `session`, that may vary across component paths.
pybids_inputs:
  spim:
    filters:
      suffix: 'spim'
      #      acquisition: 4x #this will need to be blaze4x
      subject: '001'
      extension: 'ome.zarr.zip'
    wildcards:
      - subject
      - sample
      - acquisition
      - staining


#configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:
  --skip-bids-validation:
    help: |
      Skip validation of BIDS dataset. BIDS validation is performed by
      default using the bids-validator plugin (if installed/enabled) or with the pybids
      validator implementation (if bids-validator is not installed/enabled).
    dest: "plugins.validator.skip"
    action: "store_true"
    default: False



#--- workflow specific configuration -- 


containers:
  spimprep: 'docker://khanlab/spimprep-deps:main'
  ants: 'docker://kaczmarj/ants:2.3.4'
  itksnap: 'docker://khanlab/itksnap:latest' 

root: 'results'
work: 'work'


ome_zarr:
  max_downsampling_layers: 4 # e.g. 4 levels: { 0: orig, 1: ds2, 2: ds4, 3: ds8, 4: ds16}
  rechunk_size: #z, y, x
    - 1 
    - 1024
    - 1024
  scaling_method: 'local_mean' #can be nearest, gaussian, local_mean, zoom (zoom uses spline interp)


template: ABAv3 #template to use

templates:
  ABAv3:
    anat: '{workflow.basedir}/../resources/ABAv3/P56_Atlas.nii.gz'
    dseg: '{workflow.basedir}/../resources/ABAv3/P56_Annotation.nii.gz'
    lut: '{workflow.basedir}/../resources/ABAv3/labelmapper_ABAv3_to_all.json'
  gubra:
    anat: '{workflow.basedir}/../resources/gubra/gubra_template_olf_affine_padABAv3.nii.gz'
    dseg: '{workflow.basedir}/../resources/gubra/gubra_ano_olf_affine_padABAv3_remap.nii.gz'
    lut: '{workflow.basedir}/../resources/ABAv3/labelmapper_ABAv3_to_all.json'

stains:
  - PI
  - BetaAmyloid

templatereg:
  stain: PI #set this to PI for lifecanvas data 
  level: 5
  desc: N4brain
  zooms:
    #    - 20
    - 40

masking:
  stain: PI #set this to PI for lifecanvas data 
  level: 5
  priors_template: ABAv3
  gmm_k: 9gi
  gmm_bg_class: 1
  pre_atropos_downsampling: '50%'

blobdetect:
  level: 2 #downsampling level to use for blob detection
  dseg_level: 5 # downsampling level to use for template when assigning labels to blobs
  dseg_template: ABAv3
  stain: BetaAmyloid

cellsegment:
  # CesllSeg3D parameters
  init_dataset:
    zarr: 'gs://khanlab-lightsheet/data/onuska_lifecanvas/bids/sub-o21/micr/sub-o21_sample-brain_acq-prestitched_SPIM.ome.zarr'
    num_train_chunk: 64  # number of train chunks used for training. recommended: 16384
    num_chunk_per_ld: 2048  # number of train chunk sampled from each ld; will keep sampling until reaches num_train_chunk
    creation_info: >  # '>' breaks string in yaml to multiple lines, disgarding all '\n', see https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
      This dataset is created from horizontally sampling random slices and take 32*32*32 chunks until
      there are {TOTAL_N} chunks in total. These chunks are filtered so chunks that have nothing are not included
      in the processed result. The original dataset locates at
      gs://khanlab-lightsheet/data/onuska_lifecanvas/bids/sub-o21/micr/sub-o21_sample-brain_acq-prestitched_SPIM.ome.zarr
    ld_size: !!python/tuple [32, 4096, 4096]
    train_chunk_size: !!python/tuple [32, 32, 32]
    dataset_name: "mousebrain_chan0_20240620_1"  # this will be used to name subfolders so changing this alone allows preserving results of previous runs while starting a new run

  train:
    im_channel: 1  # the channel to train on; also used for prediction
    min_brightness: 0.
    max_brightness: 1000.
    n_cuts_weight: 0.5
    rec_loss_weight: 0.005
    nepochs: 1  # recommended: 20-50
    num_classes: 5
    device: "cpu"  # the device for training/prediction
    scratch_dir: "../../../data/scratch"  # will be deleted after a rule is invoked

  predict:
    predict_range: !!python/tuple [[1344, 1386], [512, 2560], [2048, 4096]]



